In [99]:
import pandas as pd
import numpy as np

In [100]:
# Будем проверять честность монетки
# Иммитируем бросок монетки
# Первый аргумент - кол-во бросков, второй аргумент - вероятность выпадения орла
np.random.binomial(10, 0.5) # с вероятностью 50% выпадает орел , т.е. 1

6

Повторяем броски 1000 раз. И дальше считаем отклонение от 5. Потом считает процент ситуаций, в которых это отклонение >=4

# FPR

In [101]:
n = 100000
result = []

for i in range(n):
  np.random.seed(i) # делаем эксперимент воспроизовдимым (чтобы числа оставались одинаковыми)
  result.append(np.random.binomial(10, 0.5))

In [102]:
df = pd.DataFrame(result)

In [103]:
df

       0
0      5
1      5
2      5
3      5
4      8
...   ..
99995  8
99996  7
99997  7
99998  3
99999  4

[100000 rows x 1 columns]

In [104]:
# считаем отклонение
df['deviation'] = abs(5 - df[0])

In [105]:
df

       0  deviation
0      5          0
1      5          0
2      5          0
3      5          0
4      8          3
...   ..        ...
99995  8          3
99996  7          2
99997  7          2
99998  3          2
99999  4          1

[100000 rows x 2 columns]

In [106]:
# отклонение
(df['deviation'] >= 4).mean()

np.float64(0.02179)

# TPR

In [107]:
mde = 0.3

In [108]:
n = 100000
result = []

for i in range(n):
  np.random.seed(i)
  result.append(np.random.binomial(10, 0.5 + mde))

In [109]:
df = pd.DataFrame(result)

In [110]:
df

        0
0       8
1       8
2       8
3       8
4       6
...    ..
99995   6
99996   6
99997   6
99998  10
99999   9

[100000 rows x 1 columns]

In [111]:
df['deviation'] = abs(5 - df[0])

In [112]:
#df

In [113]:
(df['deviation'] >= 4).mean()

np.float64(0.37491)

# Increase FPR (Увеличиваем FPR)

## FPR

In [114]:
n = 100000
result = []
for i in range(n):
  np.random.seed(i)
  result.append(np.random.binomial(10,0.5))

In [115]:
df = pd.DataFrame(result)

In [116]:
df['deviation'] = abs(5 - df[0])

In [117]:
(df['deviation'] >= 3).mean()

np.float64(0.11145)

## TPR

In [118]:
mde = 0.3

In [119]:
n = 100000
result = []
for i in range(n):
  np.random.seed(i)
  result.append(np.random.binomial(10,0.5 + mde))

In [120]:
df = pd.DataFrame(result)

In [121]:
df['deviation'] = abs(5 - df[0])

In [122]:
(df['deviation'] >= 3).mean()

np.float64(0.67735)

# Coin Check (проверка монеты)

MDE: 10%

Power (1 - beta) : 80% - 1 - вероятность ошибки II рода, вероятность ложного пропуска

Significance (alpha): 5% - вероятность ошибки I рода

## FPR

In [135]:
sample_size = 200

In [136]:
n = 100000
result = []
for i in range(n):
  np.random.seed(i)
  result.append(np.random.binomial(sample_size,0.5))

In [137]:
df = pd.DataFrame(result)

In [138]:
df

         0
0      104
1      100
2      110
3      104
4      116
...    ...
99995  114
99996  113
99997   91
99998   96
99999   92

[100000 rows x 1 columns]

In [139]:
df['deviation'] = abs(sample_size * 0.5 - df[0])

In [143]:
# пророг
threshold = sample_size * 0.07
threshold

14.000000000000002

In [144]:
(df['deviation'] >= threshold).mean()

np.float64(0.04011)

## TPR

In [145]:
mde = 0.1

In [146]:
n = 100000
result = []
for i in range(n):
  np.random.seed(i)
  result.append(np.random.binomial(sample_size,0.5 + mde))

In [147]:
df = pd.DataFrame(result)

In [148]:
df['deviation'] = abs(sample_size * 0.5 - df[0])

In [149]:
(df['deviation'] >= threshold).mean()

np.float64(0.78681)

# Satisfaction check
H0: 80%

H1: < 80%

<br>

MDE: 10%

Power (1 - beta) : 80%

Significance (alpha): 5%

<br>

**Задача:**

нужно понять сколько человек включить в обзвон, чтобы получить характеристики выше

In [152]:
# пример рассчета. надо позвонить 100 клиентам, чтобы получить удовлетворенность 76 клиентов
np.random.binomial(100,0.8)

77

## FPR

In [209]:
sample_size = 115

In [210]:
n = 100000
result = []
for i in range(n):
  np.random.seed(i)
  result.append(np.random.binomial(sample_size,0.8))

In [211]:
df = pd.DataFrame(result)

In [212]:
df

        0
0      92
1      93
2      93
3      92
4      84
...    ..
99995  84
99996  86
99997  87
99998  98
99999  96

[100000 rows x 1 columns]

In [213]:
sample_size * 0.8

92.0

In [221]:
# отклонение
df['deviation'] = df[0] - sample_size * 0.8

In [222]:
df

        0  deviation
0      92        0.0
1      93        1.0
2      93        1.0
3      92        0.0
4      84       -8.0
...    ..        ...
99995  84       -8.0
99996  86       -6.0
99997  87       -5.0
99998  98        6.0
99999  96        4.0

[100000 rows x 2 columns]

In [223]:
# пророг
threshold = sample_size * 0.06
threshold

6.8999999999999995

In [224]:
(df['deviation'] <= -threshold).mean() # смотрим тольок на отрицательные результаты

np.float64(0.06851)

## TPR

In [192]:
mde = 0.1

In [193]:
n = 100000
result = []
for i in range(n):
  np.random.seed(i)
  result.append(np.random.binomial(sample_size,0.8 - mde))

In [194]:
df = pd.DataFrame(result)

In [195]:
df['deviation'] =  df[0] - sample_size * 0.8

In [197]:
df

        0  deviation
0      74      -18.0
1      83       -9.0
2      87       -5.0
3      79      -13.0
4      78      -14.0
...    ..        ...
99995  73      -19.0
99996  67      -25.0
99997  85       -7.0
99998  83       -9.0
99999  84       -8.0

[100000 rows x 2 columns]

In [199]:
(df['deviation'] <= -threshold).mean() # смотрим только на отрицательные результаты

np.float64(0.84279)